/* 坨坨脸 · 角色食物图鉴 —— 人物/食物名称翻译表
 *
 * ★数据来源：角色官方名与食物官方韩文名取自 트릭컬 연회장
 *   （lsbim.github.io/foods）的公开数据，2026-09 抓取。
 * ★角色日文名：lsbim 有 37 个角色 ja 字段为空、另有 5 个新角色整站未收录
 *   ——这些按「英文官方名→片假名」的转写规律补齐，属音译推定，
 *   拿到官方日文名后直接替换对应词条即可（用本工具改最方便）。
 * 结构：window.I18N_NAMES[语言id].chars / .foods = { 数据id: 译名 }
 * 食物 = 每个条目用各自的名字（基础层 30 个用 lsbim 官方韩文名，
 *   升级层按中文修饰语意译；lsbim 未收录的 8 个家族保留手工翻译）。
 * 优先级（app.js 的 charName/foodName）：本表 → 英语自动取 data.js 别名 → 中文名。
 * ★本文件由 译名编辑工具.py 生成维护；改完记得重新打包三端。
 */
(function () {
  "use strict";
  window.I18N_NAMES = {
    "en": {
      "chars": {

      },
      "foods": {
        "F1": "Strawberry Cake",
        "F10": "Lemon Tea",
        "F11": "Mysterious Grape Juice",
        "F12": "Space Rations",
        "F13": "Melon Cheese",
        "F14": "One-Bite Cabbage Wrap",
        "F15": "Honey Pot",
        "F16": "Seaweed Salad",
        "F17": "Pumpkin Soup",
        "F18": "Cinnamon Candy",
        "F19": "Ghost Pudding",
        "F2": "Chocolate Ice Cream",
        "F20": "Fried Air Sticks",
        "F21": "Gem Egg Tart",
        "F22": "Garnet Fruit",
        "F23": "Dragon Candy",
        "F24": "Golden Tanghulu",
        "F25": "Coconut Pine Porridge",
        "F26": "Honey Garlic Carp",
        "F27": "Mint Choco Ice Cream",
        "F28": "UFC Fried Radish",
        "F29": "Marshmallow Macaron",
        "F3": "Cream Pudding",
        "F30": "Bowl of Rice",
        "F31": "Sweet Vitamin C",
        "F32": "Muffin",
        "F33": "Sour Vitamin F",
        "F34": "Yule Log Cake",
        "F35": "Almond Ferrero",
        "F36": "Rice Cake Soup",
        "F37": "Aesimdang Tuo Candy",
        "F38": "Wow Strawberry Cake",
        "F39": "Elfnet Caramel Popcorn",
        "F4": "Caramel Popcorn",
        "F40": "Premium Feed Can",
        "F41": "ANSA Space Rations",
        "F42": "Whimper Honey Pot",
        "F43": "Cinnamon Health Candy",
        "F44": "Dragon Craft Candy",
        "F45": "UFC Fried Veggies",
        "F46": "Low-Sugar Marshmallow Macaron",
        "F47": "Soft-Serve Pudding",
        "F48": "Heart Knot Bread",
        "F49": "Organic Lemon Tea",
        "F5": "Feed Can",
        "F50": "Two-Bite Cabbage Wrap",
        "F51": "Fried Hydrogen Sticks",
        "F52": "Platinum Tanghulu",
        "F53": "Coconut All-Purpose Green Juice",
        "F54": "Royal Honey Garlic Carp",
        "F55": "Hot-Frozen Americano",
        "F56": "Seaweed Poke",
        "F57": "Stewed Pumpkin Soup",
        "F58": "Garnet Nectar",
        "F59": "927 Grain Powder",
        "F6": "Knot Bread",
        "F60": "Dark Choco Ice Cream",
        "F61": "Secret Grape Juice Lv.1",
        "F62": "Musk Melon Cheese",
        "F63": "Evil Spirit Pudding",
        "F64": "Treasure Egg Tart",
        "F65": "Triple Mint Choco Ice Cream",
        "F66": "Pirate Manga BBQ",
        "F67": "Sticky Rice Bowl",
        "F68": "Aesimdang Strawberry Cake",
        "F69": "Interdimensional Rations",
        "F7": "Rice Noodles",
        "F70": "Whimper Honey Jar",
        "F71": "Dragon Courage Candy",
        "F72": "UFC Full-Fry Set",
        "F73": "Snap! Caramel Popcorn",
        "F74": "Red Ginseng Health Candy",
        "F75": "Chubby Marshmallow Macaron",
        "F76": "VIP Feed Can",
        "F77": "Fried Nitrogen",
        "F78": "Triple Twist Bread",
        "F79": "Soda Fizz Lemon Tea",
        "F8": "Manga BBQ",
        "F80": "Three-Bite Cabbage Wrap",
        "F81": "Fresh Coconut Green Juice",
        "F82": "Salty Cream Brulee",
        "F83": "Jewel Tanghulu",
        "F84": "So-Hot-So-Cold Americano",
        "F85": "Garnet Shaved Ice",
        "F86": "Special Honey Garlic Salmon",
        "F87": "Seaweed Bento",
        "F88": "Pumpkin Porridge",
        "F89": "Iced Multigrain Juice",
        "F9": "Hot-Iced Americano",
        "F90": "Vitamin K",
        "X133373": "BBQ"
      }
    },
    "ko-KR": {
      "chars": {
        "Alice": "앨리스",
        "Allet": "알레트",
        "Amelia": "아멜리아",
        "AmeliaR41": "아멜리아",
        "Aragnia": "아라그니아",
        "Arco": "아르코",
        "Arnet": "아네트",
        "Asana": "아사나",
        "Ashur": "에슈르",
        "AshurMagi": "에슈르",
        "Aurora": "오로라",
        "Aya": "아야",
        "Ayla": "아일라",
        "Bana": "바나",
        "Barie": "바리에",
        "Barong": "바롱",
        "Belita": "벨리타",
        "Beni": "베니",
        "BeniBeni": "베니",
        "BigWood": "빅우드",
        "Blanchet": "블랑셰",
        "Butter": "버터",
        "Canna": "칸나",
        "Canta": "칸타",
        "Carren": "카렌",
        "Chloe": "클로에",
        "Chopi": "쵸피",
        "Cuee": "큐이",
        "Daya": "다야",
        "DayaPureShine": "다야",
        "Delia": "델리아",
        "Diana": "디아나",
        "Diana(Yester)": "디아나",
        "Ed": "이드",
        "Elena": "엘레나",
        "Epica": "에피카",
        "Erpin": "에르핀",
        "ErpinRolyale": "에르핀",
        "Espi": "에스피",
        "Festa": "페스타",
        "Fricle": "프리클",
        "Gabia": "가비아",
        "Guin": "그윈",
        "Haley": "헤일리",
        "HaleySane": "헤일리",
        "Heidi": "하이디",
        "Hilde": "힐데",
        "Ifrit": "이프리트",
        "Jade": "제이드",
        "Joanne": "죠안",
        "Jubee": "쥬비",
        "Kidian": "키디언",
        "Kishya": "키샤",
        "Kommy": "코미",
        "KommySwim": "코미",
        "Kyarot": "캬롯",
        "Laika": "라이카",
        "Lazy": "레이지",
        "Leets": "리츠",
        "Lethe": "레테",
        "Levi": "레비",
        "LeviGraduate": "레비",
        "Lion": "리온",
        "MaestroMK2": "마에스트로2호",
        "Mago": "마고",
        "Maison": "메죵",
        "Makasha": "마카샤",
        "Marie": "마리",
        "Mayo": "마요",
        "Mayo(Cool)": "마요",
        "Meluna": "멜루나",
        "Miro": "미로",
        "Momo": "모모",
        "Mute": "뮤트",
        "Mynx": "밍스",
        "Naia": "나이아",
        "Ner": "네르",
        "NerRage": "네르",
        "Neti": "네티",
        "Nicole": "니콜",
        "Opal": "오팔",
        "Orr": "오르",
        "Patula": "파트라",
        "Picora": "피코라",
        "Pira": "피라",
        "Polan": "폴랑",
        "Posher": "포셔",
        "Ran": "란",
        "Renewa": "리뉴아",
        "Rim": "림",
        "RimChaos": "림",
        "Risty": "리스티",
        "Rohne": "로네",
        "RohneMayor": "로네",
        "Rollett": "롤렛",
        "Ronnie": "로니",
        "Rude": "루드",
        "Rufo": "루포",
        "Sari": "사리",
        "Scizor": "시저",
        "Selline": "셀리네",
        "Shady": "셰이디",
        "ShadyTwisted": "셰이디",
        "Shasha": "샤샤",
        "Sherum": "셔럼",
        "Shoupan": "슈팡",
        "Silphir": "실피르",
        "Silvia": "실비아",
        "Sist": "시스트",
        "Snorky": "스노키",
        "Sparrot": "스패럿",
        "Speaki": "스피키",
        "SpeakiMaid": "스피키",
        "Suro": "슈로",
        "Sylla": "실라",
        "Taida": "타이다",
        "Tig": "티그",
        "TigHero": "티그",
        "Ui": "우이",
        "Ui(Memory)": "우이(기억)",
        "Uros": "우로스",
        "Vela": "벨라",
        "Velvet": "벨벳",
        "Veroo": "베루",
        "Vivi": "비비",
        "Vivi(Duvune)": "비비(신성)",
        "Yumimi": "유미미",
        "eisia": "아이시아",
        "inkle": "잉클",
        "kathy": "캐시",
        "ricotta": "리코타",
        "skea": "스키아",
        "xXionx": "시온",
        "yomi": "요미",
        "伊德（康复）": "이드"
      },
      "foods": {
        "F1": "딸기 케이크",
        "F10": "레몬차",
        "F11": "비밀의 포도주스",
        "F12": "우주식량",
        "F13": "멜론 보코치니",
        "F14": "한입초 쌈",
        "F15": "꿀단지",
        "F16": "해초 샐러드",
        "F17": "호박 스프",
        "F18": "계피맛 알사탕",
        "F19": "유령 푸딩",
        "F2": "초콜릿 아이스크림",
        "F20": "공기 커틀릿",
        "F21": "보석 타르트",
        "F22": "석류석 열매",
        "F23": "용족 사탕",
        "F24": "금탕후루",
        "F25": "코코넛 솔잎죽",
        "F26": "허니갈릭 살몬",
        "F27": "민트 초코 아이스크림",
        "F28": "UFC 당근 튀김",
        "F29": "마시멜로 마카롱",
        "F3": "크림 브륄레",
        "F30": "쌀밥 한 공기",
        "F31": "얌얌비타C",
        "F32": "송편",
        "F33": "새콤비타F",
        "F34": "부쉬 드 노엘",
        "F35": "아몬드 로쉐",
        "F36": "떡국",
        "F37": "에심당 뽈사탕",
        "F38": "와앙 딸기 케이크",
        "F39": "엘플릭스 캬라멜 팝콘",
        "F4": "캬라멜 팝콘",
        "F40": "고급 캔 사료",
        "F41": "ANSA 우주식량",
        "F42": "꿀꿀단지",
        "F43": "계피맛 건강 알사탕",
        "F44": "용족 세공 사탕",
        "F45": "UFC 야채 튀김",
        "F46": "저당 마시멜로 마카롱",
        "F47": "소프트 크림 브륄레",
        "F48": "하트 매듭 빵",
        "F49": "유기농 레몬차",
        "F5": "캔 사료",
        "F50": "두입초 쌈",
        "F51": "수소 커틀릿",
        "F52": "백금탕후루",
        "F53": "코코넛 만능 녹즙",
        "F54": "로얄 허니갈릭 살몬",
        "F55": "뜨거운 냉동 아메리카노",
        "F56": "해초 포케",
        "F57": "호박 스튜",
        "F58": "석류석 화채",
        "F59": "927곡 미숫가루",
        "F6": "매듭 빵",
        "F60": "딥다크 초콜릿 아이스크림",
        "F61": "1급 비밀의 포도주스",
        "F62": "머스크 멜론 보코치니",
        "F63": "악령 푸딩",
        "F64": "보물 타르트",
        "F65": "트리플 민트 초콜릿 아이스크림",
        "F66": "해적 만화 고기 구이",
        "F67": "찹쌀밥 한 공기",
        "F68": "에심당 딸기 케이크",
        "F69": "우주 차원 식량",
        "F7": "미숫가루",
        "F70": "꿀꿀꿀단지",
        "F71": "용감한 사탕",
        "F72": "UFC 모둠 튀김",
        "F73": "파팝! 캬라멜 팝콘",
        "F74": "홍삼맛 건강 알사탕",
        "F75": "빵실 마시멜로 마카롱",
        "F76": "VIP 캔 사료",
        "F77": "질소 커틀릿",
        "F78": "3단 매듭 빵",
        "F79": "스파클링 레몬차",
        "F8": "만화 고기 구이",
        "F80": "세입초 쌈",
        "F81": "코코넛 산뜻 녹즙",
        "F82": "솔티 크림 브륄레",
        "F83": "보석 탕후루",
        "F84": "앗뜨거 앗차거 아메리카노",
        "F85": "석류석 빙수",
        "F86": "스페셜 허니갈릭 살몬",
        "F87": "해초 도시락",
        "F88": "호박죽",
        "F89": "얼음 가득 미숫가루",
        "F9": "따뜻한 아이스 아메리카노",
        "F90": "킹짱비타K",
        "X133373": "구이"
      }
    },
    "ja-JP": {
      "chars": {
        "Alice": "アリス",
        "Allet": "アレット",
        "Amelia": "アメリア",
        "AmeliaR41": "アメリア",
        "Aragnia": "アラグニア",
        "Arco": "アルコ",
        "Arnet": "アネット",
        "Asana": "アサナ",
        "Ashur": "エシュール",
        "AshurMagi": "エシュール",
        "Aurora": "オーロラ",
        "Aya": "アヤ",
        "Ayla": "アイラ",
        "Bana": "バナ",
        "Barie": "バリエ",
        "Barong": "バロン",
        "Belita": "ベリータ",
        "Beni": "ベニー",
        "BeniBeni": "ベニー",
        "BigWood": "ビッグウッド",
        "Blanchet": "ブランセ",
        "Butter": "バター",
        "Canna": "カンナ",
        "Canta": "カンタ",
        "Carren": "カレン",
        "Chloe": "クロエ",
        "Chopi": "チョッピー",
        "Cuee": "キュウイ",
        "Daya": "ダーヤ",
        "DayaPureShine": "ダーヤ",
        "Delia": "ディリア",
        "Diana": "ディアナ",
        "Diana(Yester)": "ディアナ",
        "Ed": "イード",
        "Eisia": "アイシア",
        "Elena": "エレナ",
        "Epica": "エピカ",
        "Erpin": "エルフィン",
        "ErpinRolyale": "エルフィン",
        "Espi": "エスピー",
        "Festa": "フェスタ",
        "Fricle": "フリックル",
        "Gabia": "ガヴィア",
        "Gwynn": "グウィン",
        "Haley": "ヘイリー",
        "HaleySane": "ヘイリー",
        "Heidi": "ハイディ",
        "Hilde": "ヒルデ",
        "Ifrit": "イフリート",
        "Inkle": "インクル",
        "Jade": "ジェイド",
        "Joanne": "ジョアン",
        "Jubee": "ジュビー",
        "Kathy": "キャシー",
        "Kidian": "ギデオン",
        "Kishya": "キシャ",
        "Kommy": "コミー",
        "KommySwim": "コミー",
        "Kyarot": "キャロット",
        "Lazy": "レイジー",
        "Leets": "リッツ",
        "Lethe": "レテ",
        "Levi": "レヴィ",
        "LeviGraduate": "レヴィ",
        "Lion": "ライオン",
        "MaestroMK2": "マエストロ2号",
        "Mago": "マーゴ",
        "Maison": "メゾン",
        "Makasha": "マカシャ",
        "Marie": "マリー",
        "Mayo": "マヨ",
        "Mayo(Cool)": "マヨ",
        "Meluna": "メロナ",
        "Miro": "ミロ",
        "Momo": "モモ",
        "Mute": "ミュート",
        "Mynx": "ミンス",
        "Naia": "ナイア",
        "Ner": "ネル",
        "NerRage": "ネル",
        "Neti": "ネティ",
        "Nicole": "ニコル",
        "Opal": "オパール",
        "Orr": "オル",
        "Patula": "パトラ",
        "Picora": "ピコラ",
        "Pira": "ピラ",
        "Polan": "ポラン",
        "Posher": "ポーシャー",
        "Raika": "ライカ",
        "Ran": "ラン",
        "Renewa": "リニュア",
        "Ricotta": "リコッタ",
        "Rim": "リム",
        "RimChaos": "リム",
        "Risty": "リスティ",
        "Rohne": "ローネ",
        "RohneMayor": "ローネ",
        "Rollett": "ロレット",
        "Ronnie": "ロニー",
        "Rude": "ルード",
        "Rufo": "ルポ",
        "Sari": "サリー",
        "Scizor": "シーザー",
        "Selline": "セリーネ",
        "Shady": "シェイディ",
        "ShadyTwisted": "シェイディ",
        "Shasha": "シャシャ",
        "Sherum": "シェラム",
        "Shoupan": "シュパン",
        "Silphir": "シルフィール",
        "Silvia": "シルビア",
        "Sist": "シスト",
        "Skia": "スキア",
        "Snorky": "スノーキー",
        "Sparrot": "スパロット",
        "Speaki": "スピッキー",
        "SpeakiMaid": "スピッキー",
        "Suro": "シュロ",
        "Sylla": "シーラ",
        "Taida": "タイダー",
        "Tig": "ティグ",
        "TigHero": "ティグ",
        "Ui": "ウイ",
        "Ui(Memory)": "ウイ",
        "Uros": "ウロス",
        "Vela": "ベラ",
        "Velvet": "ベルベット",
        "Veroo": "ベル",
        "Vivi": "ヴィヴィ",
        "Vivi(Duvune)": "ヴィヴィ",
        "Yumimi": "ユミミ",
        "xXionx": "シオン",
        "yomi": "ヨミ",
        "伊德（康复）": "イード"
      },
      "foods": {
        "F1": "イチゴケーキ",
        "F10": "レモンティー",
        "F11": "不思議なブドウジュース",
        "F12": "宇宙食糧",
        "F13": "メロンチーズ",
        "F14": "ひと口キャベツ包み",
        "F15": "はちみつ壺",
        "F16": "海藻サラダ",
        "F17": "かぼちゃスープ",
        "F18": "シナモンキャンディ",
        "F19": "ゴーストプリン",
        "F2": "チョコアイス",
        "F20": "空気揚げ",
        "F21": "ジェムエッグタルト",
        "F22": "ガーネットの実",
        "F23": "ドラゴンキャンディ",
        "F24": "ゴールデンタンフルー",
        "F25": "ココナッツ松葉粥",
        "F26": "ハニーガーリック鯉",
        "F27": "ミントチョコアイス",
        "F28": "UFC 揚げ大根",
        "F29": "マシュマロマカロン",
        "F3": "クリームプリン",
        "F30": "ごはん一杯",
        "F31": "あまあまビタミンC",
        "F32": "マフィン",
        "F33": "すっぱビタミンF",
        "F34": "ブッシュドノエル",
        "F35": "アーモンドフェレロ",
        "F36": "お餅スープ",
        "F37": "愛心堂トトキャンディ",
        "F38": "うわっイチゴケーキ",
        "F39": "フェアネットキャラメルポップコーン",
        "F4": "キャラメルポップコーン",
        "F40": "高級エサ缶",
        "F41": "ANSA宇宙食糧",
        "F42": "うぐぅ蜜壺",
        "F43": "シナモン健康キャンディ",
        "F44": "ドラゴン細工キャンディ",
        "F45": "UFC野菜揚げ",
        "F46": "低糖マシュマロマカロン",
        "F47": "ソフトクリームプリン",
        "F48": "ハート結びパン",
        "F49": "オーガニックレモンティー",
        "F5": "エサ缶",
        "F50": "ふた口キャベツ包み",
        "F51": "水素揚げ",
        "F52": "プラチナタンフルー",
        "F53": "ココナッツ万能グリーンジュース",
        "F54": "ロイヤルハニーガーリック鯉",
        "F55": "ホットフローズンアメリカーノ",
        "F56": "海藻ポケ",
        "F57": "煮込みかぼちゃスープ",
        "F58": "ガーネットの甘露",
        "F59": "927穀物パウダー",
        "F6": "結びパン",
        "F60": "ダークチョコアイス",
        "F61": "一級秘密のブドウジュース",
        "F62": "マスクメロンチーズ",
        "F63": "悪霊プリン",
        "F64": "宝物エッグタルト",
        "F65": "トリプルミントチョコアイス",
        "F66": "海賊マンガ焼肉",
        "F67": "もち米ごはん",
        "F68": "愛心堂イチゴケーキ",
        "F69": "宇宙次元食糧",
        "F7": "ライスヌードル",
        "F70": "うぐぅ蜜瓶",
        "F71": "ドラゴン度胸キャンディ",
        "F72": "UFC全部揚げセット",
        "F73": "ぱちぱち！キャラメルポップコーン",
        "F74": "紅参健康キャンディ",
        "F75": "ぷにぷにマシュマロマカロン",
        "F76": "VIPエサ缶",
        "F77": "窒素揚げ",
        "F78": "三層ねじりパン",
        "F79": "炭酸レモンティー",
        "F8": "マンガ焼肉",
        "F80": "三口キャベツ包み",
        "F81": "新鮮ココナッツグリーンジュース",
        "F82": "しお味クレームブリュレ",
        "F83": "宝石タンフルー",
        "F84": "あつあつひんやりアメリカーノ",
        "F85": "ガーネットかき氷",
        "F86": "特製ハニーガーリックサーモン",
        "F87": "海藻弁当",
        "F88": "かぼちゃ粥",
        "F89": "氷たっぷり穀物ジュース",
        "F9": "ホットアイスアメリカーノ",
        "F90": "ビタミンK",
        "X133373": "焼肉"
      }
    }
  };
})();
