/* 坨坨脸 · 角色食物图鉴 —— 人物/食物名称翻译表
 *
 * ★数据来源：角色官方名与食物官方韩文名取自 트릭컬 연회장
 *   （lsbim.github.io/foods）的公开数据，2026-09 抓取。
 * ★角色日文名：lsbim 有 37 个角色 ja 字段为空、另有 5 个新角色整站未收录
 *   ——这些按「英文官方名→片假名」的转写规律补齐，属音译推定，
 *   拿到官方日文名后直接替换对应词条即可（用本工具改最方便）。
 * 结构：window.I18N_NAMES[语言id].chars / .foods = { 数据id: 译名 }
 * 食物 = 30 个官方家族名 + 层级后缀（+1/+2 = 升级版，中文原名见卡片小字行）；
 *   lsbim 未收录的 8 个家族保留手工翻译。
 * 优先级（app.js 的 charName/foodName）：本表 → 英语自动取 data.js 别名 → 中文名。
 * ★本文件由 译名编辑工具.py 生成维护；改完记得重新打包三端。
 */
(function () {
  "use strict";
  window.I18N_NAMES = {
    "en": {
      "chars": {

      },
      "foods": {
        "F1": "Strawberry Cake",
        "F10": "Lemon Tea",
        "F11": "Mysterious Grape Juice",
        "F12": "Space Rations",
        "F13": "Melon Cheese",
        "F14": "One-Bite Cabbage Wrap",
        "F15": "Honey Pot",
        "F16": "Seaweed Salad",
        "F17": "Pumpkin Soup",
        "F18": "Cinnamon Candy",
        "F19": "Ghost Pudding",
        "F2": "Chocolate Ice Cream",
        "F20": "Fried Air Sticks",
        "F21": "Gem Egg Tart",
        "F22": "Garnet Fruit",
        "F23": "Dragon Candy",
        "F24": "Golden Tanghulu",
        "F25": "Coconut Pine Porridge",
        "F26": "Honey Garlic Carp",
        "F27": "Mint Choco Ice Cream",
        "F28": "UFC Fried Radish",
        "F29": "Marshmallow Macaron",
        "F3": "Cream Pudding",
        "F30": "Bowl of Rice",
        "F31": "Sweet Vitamin C",
        "F32": "Muffin",
        "F33": "Sour Vitamin F",
        "F34": "Yule Log Cake",
        "F35": "Almond Ferrero",
        "F36": "Rice Cake Soup",
        "F37": "Aesimdang Tuo Candy",
        "F38": "Strawberry Cake +1",
        "F39": "Caramel Popcorn +1",
        "F4": "Caramel Popcorn",
        "F40": "Feed Can +1",
        "F41": "Space Rations +1",
        "F42": "Honey Pot +1",
        "F43": "Cinnamon Candy +1",
        "F44": "Dragon Candy +1",
        "F45": "UFC Fried Radish +1",
        "F46": "Marshmallow Macaron +1",
        "F47": "Cream Pudding +1",
        "F48": "Knot Bread +1",
        "F49": "Lemon Tea +1",
        "F5": "Feed Can",
        "F50": "One-Bite Cabbage Wrap +1",
        "F51": "Fried Air Sticks +1",
        "F52": "Golden Tanghulu +1",
        "F53": "Coconut Pine Porridge +1",
        "F54": "Honey Garlic Carp +1",
        "F55": "Hot-Iced Americano +1",
        "F56": "Seaweed Salad +2",
        "F57": "Pumpkin Soup +1",
        "F58": "Garnet Fruit +1",
        "F59": "Rice Noodles +1",
        "F6": "Knot Bread",
        "F60": "Chocolate Ice Cream +1",
        "F61": "Mysterious Grape Juice +1",
        "F62": "Melon Cheese +1",
        "F63": "Ghost Pudding +1",
        "F64": "Gem Egg Tart +1",
        "F65": "Mint Choco Ice Cream +1",
        "F66": "Manga BBQ +1",
        "F67": "Bowl of Rice +1",
        "F68": "Strawberry Cake +2",
        "F69": "Space Rations +2",
        "F7": "Rice Noodles",
        "F70": "Honey Pot +2",
        "F71": "Dragon Candy +2",
        "F72": "UFC Fried Radish +2",
        "F73": "Caramel Popcorn +2",
        "F74": "Cinnamon Candy +2",
        "F75": "Marshmallow Macaron +2",
        "F76": "Feed Can +2",
        "F77": "Fried Air Sticks +2",
        "F78": "Knot Bread +2",
        "F79": "Lemon Tea +2",
        "F8": "Manga BBQ",
        "F80": "One-Bite Cabbage Wrap +2",
        "F81": "Coconut Pine Porridge +2",
        "F82": "Cream Pudding +2",
        "F83": "Golden Tanghulu +2",
        "F84": "Hot-Iced Americano +2",
        "F85": "Garnet Fruit +2",
        "F86": "Honey Garlic Carp +2",
        "F87": "Seaweed Salad +1",
        "F88": "Pumpkin Soup +2",
        "F89": "Rice Noodles +2",
        "F9": "Hot-Iced Americano",
        "F90": "Vitamin K",
        "X133373": "BBQ"
      }
    },
    "ko-KR": {
      "chars": {
        "Alice": "앨리스",
        "Allet": "알레트",
        "Amelia": "아멜리아",
        "AmeliaR41": "아멜리아",
        "Aragnia": "아라그니아",
        "Arco": "아르코",
        "Arnet": "아네트",
        "Asana": "아사나",
        "Ashur": "에슈르",
        "AshurMagi": "에슈르",
        "Aurora": "오로라",
        "Aya": "아야",
        "Ayla": "아일라",
        "Bana": "바나",
        "Barie": "바리에",
        "Barong": "바롱",
        "Belita": "벨리타",
        "Beni": "베니",
        "BeniBeni": "베니",
        "BigWood": "빅우드",
        "Blanchet": "블랑셰",
        "Butter": "버터",
        "Canna": "칸나",
        "Canta": "칸타",
        "Carren": "카렌",
        "Chloe": "클로에",
        "Chopi": "쵸피",
        "Cuee": "큐이",
        "Daya": "다야",
        "DayaPureShine": "다야",
        "Delia": "델리아",
        "Diana": "디아나",
        "Diana(Yester)": "디아나",
        "Ed": "이드",
        "Elena": "엘레나",
        "Epica": "에피카",
        "Erpin": "에르핀",
        "ErpinRolyale": "에르핀",
        "Espi": "에스피",
        "Festa": "페스타",
        "Fricle": "프리클",
        "Gabia": "가비아",
        "Guin": "그윈",
        "Haley": "헤일리",
        "HaleySane": "헤일리",
        "Heidi": "하이디",
        "Hilde": "힐데",
        "Ifrit": "이프리트",
        "Jade": "제이드",
        "Joanne": "죠안",
        "Jubee": "쥬비",
        "Kidian": "키디언",
        "Kishya": "키샤",
        "Kommy": "코미",
        "KommySwim": "코미",
        "Kyarot": "캬롯",
        "Laika": "라이카",
        "Lazy": "레이지",
        "Leets": "리츠",
        "Lethe": "레테",
        "Levi": "레비",
        "LeviGraduate": "레비",
        "Lion": "리온",
        "MaestroMK2": "마에스트로2호",
        "Mago": "마고",
        "Maison": "메죵",
        "Makasha": "마카샤",
        "Marie": "마리",
        "Mayo": "마요",
        "Mayo(Cool)": "마요",
        "Meluna": "멜루나",
        "Miro": "미로",
        "Momo": "모모",
        "Mute": "뮤트",
        "Mynx": "밍스",
        "Naia": "나이아",
        "Ner": "네르",
        "NerRage": "네르",
        "Neti": "네티",
        "Nicole": "니콜",
        "Opal": "오팔",
        "Orr": "오르",
        "Patula": "파트라",
        "Picora": "피코라",
        "Pira": "피라",
        "Polan": "폴랑",
        "Posher": "포셔",
        "Ran": "란",
        "Renewa": "리뉴아",
        "Rim": "림",
        "RimChaos": "림",
        "Risty": "리스티",
        "Rohne": "로네",
        "RohneMayor": "로네",
        "Rollett": "롤렛",
        "Ronnie": "로니",
        "Rude": "루드",
        "Rufo": "루포",
        "Sari": "사리",
        "Scizor": "시저",
        "Selline": "셀리네",
        "Shady": "셰이디",
        "ShadyTwisted": "셰이디",
        "Shasha": "샤샤",
        "Sherum": "셔럼",
        "Shoupan": "슈팡",
        "Silphir": "실피르",
        "Silvia": "실비아",
        "Sist": "시스트",
        "Snorky": "스노키",
        "Sparrot": "스패럿",
        "Speaki": "스피키",
        "SpeakiMaid": "스피키",
        "Suro": "슈로",
        "Sylla": "실라",
        "Taida": "타이다",
        "Tig": "티그",
        "TigHero": "티그",
        "Ui": "우이",
        "Uros": "우로스",
        "Vela": "벨라",
        "Velvet": "벨벳",
        "Veroo": "베루",
        "Vivi": "비비",
        "Yumimi": "유미미",
        "eisia": "아이시아",
        "inkle": "잉클",
        "kathy": "캐시",
        "ricotta": "리코타",
        "skea": "스키아",
        "xXionx": "시온",
        "yomi": "요미",
        "伊德（康复）": "이드"
      },
      "foods": {
        "F1": "딸기 케이크",
        "F10": "레몬차",
        "F11": "비밀의 포도주스",
        "F12": "우주식량",
        "F13": "멜론 보코치니",
        "F14": "한입초 쌈",
        "F15": "꿀단지",
        "F16": "해초 샐러드",
        "F17": "호박 스프",
        "F18": "계피맛 알사탕",
        "F19": "유령 푸딩",
        "F2": "초콜릿 아이스크림",
        "F20": "공기 커틀릿",
        "F21": "보석 타르트",
        "F22": "석류석 열매",
        "F23": "용족 사탕",
        "F24": "금탕후루",
        "F25": "코코넛 솔잎죽",
        "F26": "허니갈릭 살몬",
        "F27": "민트 초코 아이스크림",
        "F28": "UFC 당근 튀김",
        "F29": "마시멜로 마카롱",
        "F3": "크림 브륄레",
        "F30": "쌀밥 한 공기",
        "F31": "달달 비타민C",
        "F32": "머핀",
        "F33": "새콤 비타민F",
        "F34": "유로그 케이크",
        "F35": "아몬드 페레로",
        "F36": "떡국",
        "F37": "애심당 통통사탕",
        "F38": "딸기 케이크 +1",
        "F39": "캬라멜 팝콘 +1",
        "F4": "캬라멜 팝콘",
        "F40": "캔 사료 +1",
        "F41": "우주식량 +1",
        "F42": "꿀단지 +1",
        "F43": "계피맛 알사탕 +1",
        "F44": "용족 사탕 +1",
        "F45": "UFC 당근 튀김 +1",
        "F46": "마시멜로 마카롱 +1",
        "F47": "크림 브륄레 +1",
        "F48": "매듭 빵 +1",
        "F49": "레몬차 +1",
        "F5": "캔 사료",
        "F50": "한입초 쌈 +1",
        "F51": "공기 커틀릿 +1",
        "F52": "금탕후루 +1",
        "F53": "코코넛 솔잎죽 +1",
        "F54": "허니갈릭 살몬 +1",
        "F55": "따뜻한 아이스 아메리카노 +1",
        "F56": "해초 샐러드 +2",
        "F57": "호박 스프 +1",
        "F58": "석류석 열매 +1",
        "F59": "미숫가루 +1",
        "F6": "매듭 빵",
        "F60": "초콜릿 아이스크림 +1",
        "F61": "비밀의 포도주스 +1",
        "F62": "멜론 보코치니 +1",
        "F63": "유령 푸딩 +1",
        "F64": "보석 타르트 +1",
        "F65": "민트 초코 아이스크림 +1",
        "F66": "만화 고기 구이 +1",
        "F67": "쌀밥 한 공기 +1",
        "F68": "딸기 케이크 +2",
        "F69": "우주식량 +2",
        "F7": "미숫가루",
        "F70": "꿀단지 +2",
        "F71": "용족 사탕 +2",
        "F72": "UFC 당근 튀김 +2",
        "F73": "캬라멜 팝콘 +2",
        "F74": "계피맛 알사탕 +2",
        "F75": "마시멜로 마카롱 +2",
        "F76": "캔 사료 +2",
        "F77": "공기 커틀릿 +2",
        "F78": "매듭 빵 +2",
        "F79": "레몬차 +2",
        "F8": "만화 고기 구이",
        "F80": "한입초 쌈 +2",
        "F81": "코코넛 솔잎죽 +2",
        "F82": "크림 브륄레 +2",
        "F83": "금탕후루 +2",
        "F84": "따뜻한 아이스 아메리카노 +2",
        "F85": "석류석 열매 +2",
        "F86": "허니갈릭 살몬 +2",
        "F87": "해초 샐러드 +1",
        "F88": "호박 스프 +2",
        "F89": "미숫가루 +2",
        "F9": "따뜻한 아이스 아메리카노",
        "F90": "비타민K",
        "X133373": "구이"
      }
    },
    "ja-JP": {
      "chars": {
        "Alice": "アリス",
        "Allet": "アレット",
        "Amelia": "アメリア",
        "AmeliaR41": "アメリア",
        "Aragnia": "アラグニア",
        "Arco": "アルコ",
        "Arnet": "アネット",
        "Asana": "アサナ",
        "Ashur": "エシュール",
        "AshurMagi": "エシュール",
        "Aurora": "オーロラ",
        "Aya": "アヤ",
        "Ayla": "アイラ",
        "Bana": "バナ",
        "Barie": "バリエ",
        "Barong": "バロン",
        "Belita": "ベリータ",
        "Beni": "ベニー",
        "BeniBeni": "ベニー",
        "BigWood": "ビッグウッド",
        "Blanchet": "ブランセ",
        "Butter": "バター",
        "Canna": "カンナ",
        "Canta": "カンタ",
        "Carren": "カレン",
        "Chloe": "クロエ",
        "Chopi": "チョッピー",
        "Cuee": "キュウイ",
        "Daya": "ダーヤ",
        "DayaPureShine": "ダーヤ",
        "Delia": "ディリア",
        "Diana": "ディアナ",
        "Diana(Yester)": "ディアナ",
        "Ed": "イード",
        "Eisia": "アイシア",
        "Elena": "エレナ",
        "Epica": "エピカ",
        "Erpin": "エルフィン",
        "ErpinRolyale": "エルフィン",
        "Espi": "エスピー",
        "Festa": "フェスタ",
        "Fricle": "フリックル",
        "Gabia": "ガヴィア",
        "Gwynn": "グウィン",
        "Haley": "ヘイリー",
        "HaleySane": "ヘイリー",
        "Heidi": "ハイディ",
        "Hilde": "ヒルデ",
        "Ifrit": "イフリート",
        "Inkle": "インクル",
        "Jade": "ジェイド",
        "Joanne": "ジョアン",
        "Jubee": "ジュビー",
        "Kathy": "キャシー",
        "Kidian": "ギデオン",
        "Kishya": "キシャ",
        "Kommy": "コミー",
        "KommySwim": "コミー",
        "Kyarot": "キャロット",
        "Lazy": "レイジー",
        "Leets": "リッツ",
        "Lethe": "レテ",
        "Levi": "レヴィ",
        "LeviGraduate": "レヴィ",
        "Lion": "ライオン",
        "MaestroMK2": "マエストロ2号",
        "Mago": "マーゴ",
        "Maison": "メゾン",
        "Makasha": "マカシャ",
        "Marie": "マリー",
        "Mayo": "マヨ",
        "Mayo(Cool)": "マヨ",
        "Meluna": "メロナ",
        "Miro": "ミロ",
        "Momo": "モモ",
        "Mute": "ミュート",
        "Mynx": "ミンス",
        "Naia": "ナイア",
        "Ner": "ネル",
        "NerRage": "ネル",
        "Neti": "ネティ",
        "Nicole": "ニコル",
        "Opal": "オパール",
        "Orr": "オル",
        "Patula": "パトラ",
        "Picora": "ピコラ",
        "Pira": "ピラ",
        "Polan": "ポラン",
        "Posher": "ポーシャー",
        "Raika": "ライカ",
        "Ran": "ラン",
        "Renewa": "リニュア",
        "Ricotta": "リコッタ",
        "Rim": "リム",
        "RimChaos": "リム",
        "Risty": "リスティ",
        "Rohne": "ローネ",
        "RohneMayor": "ローネ",
        "Rollett": "ロレット",
        "Ronnie": "ロニー",
        "Rude": "ルード",
        "Rufo": "ルポ",
        "Sari": "サリー",
        "Scizor": "シーザー",
        "Selline": "セリーネ",
        "Shady": "シェイディ",
        "ShadyTwisted": "シェイディ",
        "Shasha": "シャシャ",
        "Sherum": "シェラム",
        "Shoupan": "シュパン",
        "Silphir": "シルフィール",
        "Silvia": "シルビア",
        "Sist": "シスト",
        "Skia": "スキア",
        "Snorky": "スノーキー",
        "Sparrot": "スパロット",
        "Speaki": "スピッキー",
        "SpeakiMaid": "スピッキー",
        "Suro": "シュロ",
        "Sylla": "シーラ",
        "Taida": "タイダー",
        "Tig": "ティグ",
        "TigHero": "ティグ",
        "Ui": "ウイ",
        "Uros": "ウロス",
        "Vela": "ベラ",
        "Velvet": "ベルベット",
        "Veroo": "ベル",
        "Vivi": "ヴィヴィ",
        "Yumimi": "ユミミ",
        "xXionx": "シオン",
        "yomi": "ヨミ",
        "伊德（康复）": "イード"
      },
      "foods": {
        "F1": "イチゴケーキ",
        "F10": "レモンティー",
        "F11": "不思議なブドウジュース",
        "F12": "宇宙食糧",
        "F13": "メロンチーズ",
        "F14": "ひと口キャベツ包み",
        "F15": "はちみつ壺",
        "F16": "海藻サラダ",
        "F17": "かぼちゃスープ",
        "F18": "シナモンキャンディ",
        "F19": "ゴーストプリン",
        "F2": "チョコアイス",
        "F20": "空気揚げ",
        "F21": "ジェムエッグタルト",
        "F22": "ガーネットの実",
        "F23": "ドラゴンキャンディ",
        "F24": "ゴールデンタンフルー",
        "F25": "ココナッツ松葉粥",
        "F26": "ハニーガーリック鯉",
        "F27": "ミントチョコアイス",
        "F28": "UFC 揚げ大根",
        "F29": "マシュマロマカロン",
        "F3": "クリームプリン",
        "F30": "ごはん一杯",
        "F31": "あまあまビタミンC",
        "F32": "マフィン",
        "F33": "すっぱビタミンF",
        "F34": "ブッシュドノエル",
        "F35": "アーモンドフェレロ",
        "F36": "お餅スープ",
        "F37": "愛心堂トトキャンディ",
        "F38": "イチゴケーキ +1",
        "F39": "キャラメルポップコーン +1",
        "F4": "キャラメルポップコーン",
        "F40": "エサ缶 +1",
        "F41": "宇宙食糧 +1",
        "F42": "はちみつ壺 +1",
        "F43": "シナモンキャンディ +1",
        "F44": "ドラゴンキャンディ +1",
        "F45": "UFC 揚げ大根 +1",
        "F46": "マシュマロマカロン +1",
        "F47": "クリームプリン +1",
        "F48": "結びパン +1",
        "F49": "レモンティー +1",
        "F5": "エサ缶",
        "F50": "ひと口キャベツ包み +1",
        "F51": "空気揚げ +1",
        "F52": "ゴールデンタンフルー +1",
        "F53": "ココナッツ松葉粥 +1",
        "F54": "ハニーガーリック鯉 +1",
        "F55": "ホットアイスアメリカーノ +1",
        "F56": "海藻サラダ +2",
        "F57": "かぼちゃスープ +1",
        "F58": "ガーネットの実 +1",
        "F59": "ライスヌードル +1",
        "F6": "結びパン",
        "F60": "チョコアイス +1",
        "F61": "不思議なブドウジュース +1",
        "F62": "メロンチーズ +1",
        "F63": "ゴーストプリン +1",
        "F64": "ジェムエッグタルト +1",
        "F65": "ミントチョコアイス +1",
        "F66": "マンガ焼肉 +1",
        "F67": "ごはん一杯 +1",
        "F68": "イチゴケーキ +2",
        "F69": "宇宙食糧 +2",
        "F7": "ライスヌードル",
        "F70": "はちみつ壺 +2",
        "F71": "ドラゴンキャンディ +2",
        "F72": "UFC 揚げ大根 +2",
        "F73": "キャラメルポップコーン +2",
        "F74": "シナモンキャンディ +2",
        "F75": "マシュマロマカロン +2",
        "F76": "エサ缶 +2",
        "F77": "空気揚げ +2",
        "F78": "結びパン +2",
        "F79": "レモンティー +2",
        "F8": "マンガ焼肉",
        "F80": "ひと口キャベツ包み +2",
        "F81": "ココナッツ松葉粥 +2",
        "F82": "クリームプリン +2",
        "F83": "ゴールデンタンフルー +2",
        "F84": "ホットアイスアメリカーノ +2",
        "F85": "ガーネットの実 +2",
        "F86": "ハニーガーリック鯉 +2",
        "F87": "海藻サラダ +1",
        "F88": "かぼちゃスープ +2",
        "F89": "ライスヌードル +2",
        "F9": "ホットアイスアメリカーノ",
        "F90": "ビタミンK",
        "X133373": "焼肉"
      }
    }
  };
})();
