/* 坨坨脸 · 角色食物图鉴 —— 人物/食物名称翻译表
 *
 * 结构：window.I18N_NAMES[语言id].chars / .foods = { 数据id: 译名 }
 * 优先级（app.js 的 charName/foodName）：
 *   1. 本表对应语言的译名
 *   2. 英语模式：角色自动取 data.js aliases 里第一个纯英文名
 *   3. 都没有 → 显示 data.js 的中文名（不裂、不丢）
 * ★角色韩/日官译名（游戏是韩国游戏，韩文就是官方名）以后可从韩服 wiki 补进
 *   下面的 chars 表；补完重跑 美化工作区\subset_font.py 更新字体子集。
 */
(function () {
  "use strict";
  window.I18N_NAMES = {
    "en": {
      "chars": {
        // 例： "Uros": "Uros"（英语角色名已自动取别名，一般不用填）
      },
      "foods": {
        "F1": "Strawberry Cake",
        "F2": "Chocolate Ice Cream",
        "F3": "Cream Pudding",
        "F4": "Caramel Popcorn",
        "F5": "Feed Can",
        "F6": "Knot Bread",
        "F7": "Rice Noodles",
        "F8": "Manga BBQ",
        "F9": "Hot-Iced Americano",
        "F10": "Lemon Tea",
        "F11": "Mysterious Grape Juice",
        "F12": "Space Rations",
        "F13": "Melon Cheese",
        "F14": "One-Bite Cabbage Wrap",
        "F15": "Honey Pot",
        "F16": "Seaweed Salad",
        "F17": "Pumpkin Soup",
        "F18": "Cinnamon Candy",
        "F19": "Ghost Pudding",
        "F20": "Fried Air Sticks",
        "F21": "Gem Egg Tart",
        "F22": "Garnet Fruit",
        "F23": "Dragon Candy",
        "F24": "Golden Tanghulu",
        "F25": "Coconut Pine Porridge",
        "F26": "Honey Garlic Carp",
        "F27": "Mint Choco Ice Cream",
        "F28": "UFC Fried Radish",
        "F29": "Marshmallow Macaron",
        "F30": "Bowl of Rice",
        "F31": "Sweet Vitamin C",
        "F32": "Muffin",
        "F33": "Sour Vitamin F",
        "F34": "Yule Log Cake",
        "F35": "Almond Ferrero",
        "F36": "Rice Cake Soup",
        "F37": "Aesimdang Tuo Candy",
        "F38": "Wow Strawberry Cake",
        "F39": "Elfnet Caramel Popcorn",
        "F40": "Premium Feed Can",
        "F41": "ANSA Space Rations",
        "F42": "Whimper Honey Pot",
        "F43": "Cinnamon Health Candy",
        "F44": "Dragon Craft Candy",
        "F45": "UFC Fried Veggies",
        "F46": "Low-Sugar Marshmallow Macaron",
        "F47": "Soft-Serve Pudding",
        "F48": "Heart Knot Bread",
        "F49": "Organic Lemon Tea",
        "F50": "Two-Bite Cabbage Wrap",
        "F51": "Fried Hydrogen Sticks",
        "F52": "Platinum Tanghulu",
        "F53": "Coconut All-Purpose Green Juice",
        "F54": "Royal Honey Garlic Carp",
        "F55": "Hot-Frozen Americano",
        "F56": "Seaweed Poke",
        "F57": "Stewed Pumpkin Soup",
        "F58": "Garnet Nectar",
        "F59": "927 Grain Powder",
        "F60": "Dark Choco Ice Cream",
        "F61": "Mysterious Grape Juice (Lv.1)",
        "F62": "Musk Melon Cheese",
        "F63": "Evil Spirit Pudding",
        "F64": "Treasure Egg Tart",
        "F65": "Triple Mint Choco Ice Cream",
        "F66": "Pirate Manga BBQ",
        "F67": "Bowl of Sticky Rice",
        "X133373": "BBQ",
        "F68": "Aesimdang Strawberry Cake",
        "F69": "Interdimensional Rations",
        "F70": "Whimper Honey Jar",
        "F71": "Dragon Courage Candy",
        "F72": "UFC Full-Fry Set",
        "F73": "Snap! Caramel Popcorn",
        "F74": "Red Ginseng Health Candy",
        "F75": "Chubby Marshmallow Macaron",
        "F76": "VIP Feed Can",
        "F77": "Fried Nitrogen",
        "F78": "Triple Twist Bread",
        "F79": "Soda Fizz Lemon Tea",
        "F80": "Three-Bite Cabbage Wrap",
        "F81": "Fresh Coconut Green Juice",
        "F82": "Salty Cream Brulee",
        "F83": "Jewel Tanghulu",
        "F84": "So-Hot-So-Cold Americano",
        "F85": "Garnet Shaved Ice",
        "F86": "Special Honey Garlic Salmon",
        "F87": "Seaweed Bento",
        "F88": "Pumpkin Porridge",
        "F89": "Iced Multigrain Juice"
      }
    },
    "ko-KR": {
      "chars": {
        // 例： "Uros": "우로스"（韩服官方角色名可在此补齐）
      },
      "foods": {
        "F1": "딸기케이크",
        "F2": "초코아이스크림",
        "F3": "크림푸딩",
        "F4": "캬라멜팝콘",
        "F5": "사료캔",
        "F6": "매듭빵",
        "F7": "쌀국수",
        "F8": "만화구이",
        "F9": "핫아이스 아메리카노",
        "F10": "레몬차",
        "F11": "신비한 포도주스",
        "F12": "우주식량",
        "F13": "멜론치즈",
        "F14": "한입 양배추쌈",
        "F15": "꿀단지",
        "F16": "해조류 샐러드",
        "F17": "호박수프",
        "F18": "계피사탕",
        "F19": "유령푸딩",
        "F20": "공기튀김",
        "F21": "보석 에그타르트",
        "F22": "가넷 열매",
        "F23": "용족 사탕",
        "F24": "황금 탕후루",
        "F25": "코코넛 솔잎죽",
        "F26": "꿀마늘 잉어구이",
        "F27": "민트초코아이스크림",
        "F28": "UFC 튀긴 무",
        "F29": "마시멜로 마카롱",
        "F30": "밥 한 그릇",
        "F31": "달달 비타민C",
        "F32": "머핀",
        "F33": "새콤 비타민F",
        "F34": "유로그 케이크",
        "F35": "아몬드 페레로",
        "F36": "떡국",
        "F37": "애심당 통통사탕",
        "F38": "우와 딸기케이크",
        "F39": "요정넷 캬라멜팝콘",
        "F40": "고급 사료캔",
        "F41": "ANSA 우주식량",
        "F42": "끙끙 꿀단지",
        "F43": "계피 건강사탕",
        "F44": "용족 세공사탕",
        "F45": "UFC 튀긴 야채",
        "F46": "저당 마시멜로 마카롱",
        "F47": "소프트 아이스크림 푸딩",
        "F48": "하트 매듭빵",
        "F49": "유기농 레몬차",
        "F50": "두입 양배추쌈",
        "F51": "수소튀김",
        "F52": "플래티넘 탕후루",
        "F53": "코코넛 만능 그린주스",
        "F54": "로얄 꿀마늘 잉어구이",
        "F55": "핫프로즌 아메리카노",
        "F56": "해조류 포키",
        "F57": "호박스프 찜",
        "F58": "가넷 감로",
        "F59": "927 곡물가루",
        "F60": "다크초코아이스크림",
        "F61": "1급 신비한 포도주스",
        "F62": "머스크 멜론치즈",
        "F63": "악령 푸딩",
        "F64": "보물 에그타르트",
        "F65": "트리플 민트초코아이스크림",
        "F66": "해적 만화구이",
        "F67": "찹쌀밥 한 그릇",
        "X133373": "구이",
        "F68": "애심당 딸기케이크",
        "F69": "우주차원 식량",
        "F70": "끙끙 꿀통",
        "F71": "용감사탕",
        "F72": "UFC 풀튀김 세트",
        "F73": "짝짝! 캬라멜팝콘",
        "F74": "홍삼 건강사탕",
        "F75": "뚱뚱한 마시멜로 마카롱",
        "F76": "VIP 사료캔",
        "F77": "튀긴 질소",
        "F78": "세 층 꽈배기빵",
        "F79": "사이다 레몬차",
        "F80": "세입 양배추쌈",
        "F81": "신선 코코넛 그린주스",
        "F82": "짭짤 크렘브륄레",
        "F83": "주얼 탕후루",
        "F84": "뜨겁차 아메리카노",
        "F85": "가넷 빙수",
        "F86": "특제 꿀마늘 연어구이",
        "F87": "해조류 도시락",
        "F88": "호박죽",
        "F89": "얼음 가득 곡물주스"
      }
    },
    "ja-JP": {
      "chars": {
        // 例： "Uros": "ウロス"（日服官方角色名可在此补齐）
      },
      "foods": {
        "F1": "イチゴケーキ",
        "F2": "チョコアイス",
        "F3": "クリームプリン",
        "F4": "キャラメルポップコーン",
        "F5": "エサ缶",
        "F6": "結びパン",
        "F7": "ライスヌードル",
        "F8": "マンガ焼肉",
        "F9": "ホットアイスアメリカーノ",
        "F10": "レモンティー",
        "F11": "不思議なブドウジュース",
        "F12": "宇宙食糧",
        "F13": "メロンチーズ",
        "F14": "ひと口キャベツ包み",
        "F15": "はちみつ壺",
        "F16": "海藻サラダ",
        "F17": "かぼちゃスープ",
        "F18": "シナモンキャンディ",
        "F19": "ゴーストプリン",
        "F20": "空気揚げ",
        "F21": "ジェムエッグタルト",
        "F22": "ガーネットの実",
        "F23": "ドラゴンキャンディ",
        "F24": "ゴールデンタンフルー",
        "F25": "ココナッツ松葉粥",
        "F26": "ハニーガーリック鯉",
        "F27": "ミントチョコアイス",
        "F28": "UFC 揚げ大根",
        "F29": "マシュマロマカロン",
        "F30": "ごはん一杯",
        "F31": "あまあまビタミンC",
        "F32": "マフィン",
        "F33": "すっぱビタミンF",
        "F34": "ブッシュドノエル",
        "F35": "アーモンドフェレロ",
        "F36": "お餅スープ",
        "F37": "愛心堂トトキャンディ",
        "F38": "うわっイチゴケーキ",
        "F39": "フェアネットキャラメルポップコーン",
        "F40": "高級エサ缶",
        "F41": "ANSA宇宙食糧",
        "F42": "うぐぅはちみつ壺",
        "F43": "シナモン健康キャンディ",
        "F44": "ドラゴン細工キャンディ",
        "F45": "UFC 揚げ野菜",
        "F46": "低糖マシュマロマカロン",
        "F47": "ソフトクリームプリン",
        "F48": "ハート結びパン",
        "F49": "オーガニックレモンティー",
        "F50": "ふた口キャベツ包み",
        "F51": "水素揚げ",
        "F52": "プラチナタンフルー",
        "F53": "ココナッツ万能グリーンジュース",
        "F54": "ロイヤルハニーガーリック鯉",
        "F55": "ホットフローズンアメリカーノ",
        "F56": "海藻ポキ",
        "F57": "煮込みかぼちゃスープ",
        "F58": "ガーネットの甘露",
        "F59": "927穀物パウダー",
        "F60": "ダークチョコアイス",
        "F61": "一級不思議なブドウジュース",
        "F62": "マスクメロンチーズ",
        "F63": "悪霊プリン",
        "F64": "宝物エッグタルト",
        "F65": "トリプルミントチョコアイス",
        "F66": "海賊マンガ焼肉",
        "F67": "もち米ごはん一杯",
        "X133373": "焼肉",
        "F68": "愛心堂イチゴケーキ",
        "F69": "宇宙次元食糧",
        "F70": "うぐぅはちみつ瓶",
        "F71": "ドラゴン度胸キャンディ",
        "F72": "UFC 全揚げセット",
        "F73": "ぱちぱち！キャラメルポップコーン",
        "F74": "紅参健康キャンディ",
        "F75": "ぷにぷにマシュマロマカロン",
        "F76": "VIPエサ缶",
        "F77": "揚げ窒素",
        "F78": "三層ねじりパン",
        "F79": "炭酸レモンティー",
        "F80": "三口キャベツ包み",
        "F81": "新鮮ココナッツグリーンジュース",
        "F82": "しお味クレームブリュレ",
        "F83": "ジュエルタンフルー",
        "F84": "あつあつひんやりアメリカーノ",
        "F85": "ガーネットかき氷",
        "F86": "特製はちみつニンニクサーモン",
        "F87": "海藻弁当",
        "F88": "かぼちゃ粥",
        "F89": "氷たっぷり穀物ジュース"
      }
    }
  };
})();
